### PR TITLE
Better install.sh

### PR DESCRIPTION
**Pull request by ghost**
Re-written in Bash 4, supports both Darwin and (most) Linux distributions.
Easier to add support for more distributions.
Installs dependencies after checking those missing from system.
Checks for running servers (redis, postgres) and/or starts them as required.
Sets up postgres DBs and runs app.

### CODE REVIEW

**Comment by aravindet** [comment]
Just remembered one more issue: we need postgres 9.4, but the distros (except arch) probably have older in their repositories.

sbentity.sql will fail on pgsql<=9.3

:-(

**Comment by sindhus** [comment]
Noted, will try to support this.

**Comment by sindhus** [comment]
Yesterday tested out manually on OSX, seems to work. I have put Docker to build our script automatically in Arch, Ubuntu, Debian and Fedora images. Build status [here](https://registry.hub.docker.com/u/sindhus/scrollback-docker-builds/builds_history/160657/). Dockerfiles [here](https://github.com/sindhus/scrollback-docker-builds).

**Comment by sindhus** [comment]
Also please ignore other commits clubbed along with mine. It's a result of cherry-picking/rebasing (scattered work across clientrefactor, master branches).

**Comment by aravindet** [comment]
Could you rebase this on master and fix the conflicts?

**Comment by sindhus** [comment]
Have rebased against master. 
* Tested as user with sudo rights inside a docker container for Ubuntu. Installs system deps and npm deps (both global and local), creates config files, checks for running servers, starts them if not -- as expected.
* __Untested__ for Debian (but should mostly work because both use init and apt-get)
* __Untested__ for Arch Linux and Fedora.

Should everything go right, all user has to do is open up http://localhost:7528 to see Scrollback running.

Much of the delay in testing was because I wasn't aware that:
1. docker doesn't allow to run sudo within container, 
2. not knowing the postgresql, nodejs package name conflicts in Ubuntu and 
3. fixing a ton of edge cases which is a side-effect of trying to automate everything for user :) 
More development notes [here](http://sindhus.github.io/install-script-for-scrollback/) if anyone is interested in reading.

**Comment by aravindet** [comment]
Awesome! Will review and merge.

**Comment by sindhus** [comment]
Thank you!

**Pull request merged**
