### PR TITLE
Emoticons

### PR DESCRIPTION
**Pull request by amalantony**

### CODE REVIEW

**Comment by satya164** [comment]
Info area should also have markdown support - https://github.com/scrollback/scrollback/issues/460

**Comment by amalantony** [comment]
@satya164 Info area will have MD support as well when this pull request is merged.

**Comment by aravindet** [comment]
IIUC, all we need to do to finish this is remove our remarkable-emoji and hook up the standard one that they have released?

**Comment by amalantony** [comment]
@aravindet Yes, that would suffice.

**Comment by amalantony** [comment]
@aravindet, this pull request can be merged.

**Pull request merged**
