### PR TITLE
Added few dependencies.

### PR DESCRIPTION
**Pull request by sagarhani**
Few of the dependencies which were required to install manually during the process of installing Scrollback are added here. So, now these dependencies will be installed automatically when we execute install.sh. :+1:

### CODE REVIEW

**Comment by satya164** [comment]
A quick search doesn't show any occurrences of these two modules. I think they are instead dependencies of some module which didn't install properly due to some error.

**Comment by sagarhani** [comment]
When I did : 
```
npm start
```
It was throwing an error telling these modules are missing. I had to install these modules manually to run the Scrollback.

Anyways, I'll try to install it again in other machine and check it out once. :+1:

**Comment by satya164** [comment]
@sagarhani Try looking at the stack trace to find out where did the error originate.

**Comment by aravindet** [comment]
Doing a `grep -r "require("` and cleaning up, here is a full list of dependencies. Use this please:

```
blanket
bower
browserify
browserstack-webdriver
del
ebus
elasticsearch
event-stream
express
gulp
gulp-autoprefixer
gulp-combine-mq
gulp-concat
gulp-gitmodified
gulp-jscs
gulp-jshint
gulp-manifest
gulp-minify-css
gulp-notify
gulp-plumber
gulp-rename
gulp-sass
gulp-sourcemaps
gulp-strip-debug
gulp-sym
gulp-uglify
gulp-util
handlebars
htmlencode
irc
jade
jsonwebtoken
lazypipe
markdown-it
markdown-it-emoji
mysql
newrelic
nodemailer
oauth
objectlevel
path").normalize(__dirname + 
pg
q
redis
request
secure-random
sockjs
twit
underscore
util
valid
vinyl-buffer
vinyl-source-stream
winston
```

**Comment by aravindet** [comment]
Also, it would be nice to automate that process. Search for "require(" throughout the codebase, extract the arguments, filter out relative paths (they begin with a . or ..), filter out the node builtin modules, you're left with the list of actual dependencies.

**Comment by sindhus** [comment]
@sagarhani hi! We have fixed the issue in #523. You can pull from master and try with `npm install` again :)

**Pull request closed without merging**
